# Generated by Django 6.0.6 on 2026-07-20 16:52

import django.db.models.deletion
import iam.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0172_view_compliance_assessment_full_permission'),
        ('iam', '0022_user_is_scim_managed_user_scim_external_id_idpgroup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Contract reference')),
                ('hours_model', models.CharField(choices=[('none', 'No hours tracking'), ('budget', 'Budget + capacity'), ('timelog', 'Time-logging'), ('hybrid', 'Hybrid')], default='budget', max_length=20, verbose_name='Hours model')),
                ('contracted_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Contracted hours')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hourly rate (override of global daily rate / 8)')),
                ('day_zero', models.DateField(blank=True, null=True, verbose_name='Day zero (plan anchor)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('sla', models.JSONField(blank=True, default=dict, verbose_name='SLA')),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('onboarding', 'Onboarding'), ('active', 'Active'), ('paused', 'Paused'), ('offboarding', 'Offboarding'), ('closed', 'Closed')], default='onboarding', max_length=20, verbose_name='Status')),
                ('folder', models.ForeignKey(default=iam.models.Folder.get_root_folder_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder')),
                ('perimeter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_engagements', to='core.perimeter', verbose_name='Perimeter')),
            ],
            options={
                'verbose_name': 'Engagement',
                'verbose_name_plural': 'Engagements',
            },
        ),
        migrations.CreateModel(
            name='ClientIntake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('subsector', models.CharField(blank=True, choices=[('bank', 'Bank / credit institution'), ('asset_manager', 'Asset manager (ANBIMA)'), ('broker', 'Broker / DTVM (CVM)'), ('other', 'Other / hybrid')], max_length=30)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True)),
                ('contacts', models.JSONField(blank=True, default=dict)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('assets_seed', models.JSONField(blank=True, default=list)),
                ('provisioning_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('provisioned', 'Provisioned')], default='draft', max_length=20)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('folder', models.ForeignKey(default=iam.models.Folder.get_root_folder_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder')),
                ('primary_frameworks', models.ManyToManyField(blank=True, related_name='delivery_intakes', to='core.framework')),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intakes', to='delivery.engagement')),
            ],
            options={
                'verbose_name': 'Client intake',
                'verbose_name_plural': 'Client intakes',
            },
        ),
        migrations.CreateModel(
            name='EngagementPhase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('day_start', models.PositiveSmallIntegerField(default=0)),
                ('day_end', models.PositiveSmallIntegerField(default=30)),
                ('objective', models.TextField(blank=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='delivery.engagement')),
                ('folder', models.ForeignKey(default=iam.models.Folder.get_root_folder_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder')),
                ('organisation_objective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_phases', to='core.organisationobjective')),
            ],
            options={
                'verbose_name': 'Engagement phase',
                'verbose_name_plural': 'Engagement phases',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PlanTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('urgency_override', models.SmallIntegerField(blank=True, null=True)),
                ('importance_override', models.SmallIntegerField(blank=True, null=True)),
                ('template_key', models.CharField(blank=True, db_index=True, max_length=150)),
                ('applied_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_plan_task', to='core.appliedcontrol')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_tasks', to='delivery.engagement')),
                ('folder', models.ForeignKey(default=iam.models.Folder.get_root_folder_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='delivery.engagementphase')),
                ('task_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_plan_task', to='core.tasktemplate')),
            ],
            options={
                'verbose_name': 'Plan task',
                'verbose_name_plural': 'Plan tasks',
                'ordering': ['phase__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField()),
                ('billable', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('applied_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_time_entries', to='core.appliedcontrol')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='delivery.engagement')),
                ('folder', models.ForeignKey(default=iam.models.Folder.get_root_folder_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder')),
                ('plan_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='delivery.plantask')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_time_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Time entry',
                'verbose_name_plural': 'Time entries',
            },
        ),
        migrations.AddConstraint(
            model_name='engagement',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('folder',), name='unique_active_engagement_per_folder'),
        ),
        migrations.AddConstraint(
            model_name='plantask',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('applied_control__isnull', False), ('task_template__isnull', True)), models.Q(('applied_control__isnull', True), ('task_template__isnull', False)), _connector='OR'), name='plantask_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='plantask',
            constraint=models.UniqueConstraint(condition=models.Q(('template_key', ''), _negated=True), fields=('engagement', 'template_key'), name='unique_plantask_template_key_per_engagement'),
        ),
    ]
