# Generated by Django 6.0.6 on 2026-07-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='branding/clients/', verbose_name='Client logo'),
        ),
    ]
