# Generated by Django 6.0.6 on 2026-07-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_engagement_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='website',
            field=models.CharField(blank=True, max_length=255, verbose_name='Client website/domain'),
        ),
    ]
