# Generated by Django 6.0.6 on 2026-07-21 02:22

import django.db.models.deletion
import iam.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0172_view_compliance_assessment_full_permission'),
        ('delivery', '0003_engagement_website'),
        ('iam', '0022_user_is_scim_managed_user_scim_external_id_idpgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('ref_id', models.CharField(blank=True, max_length=100)),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Criticality')),
                ('collaborators', models.PositiveIntegerField(default=0, verbose_name='Collaborators using the catalog')),
                ('collaborator_hourly_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Collaborator hourly cost (fallback: global daily rate / 8)')),
                ('hourly_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Hourly revenue generated')),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Profit margin (%) for lost profit')),
                ('regulatory_hourly', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Regulatory penalty per hour')),
                ('regulatory_fixed', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Fixed regulatory penalty per incident')),
                ('maintenance_extra_annual', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Extra annual maintenance cost (beyond dependencies)')),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogs', to='delivery.engagement')),
                ('folder', models.ForeignKey(default=iam.models.Folder.get_root_folder_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder')),
            ],
            options={
                'verbose_name': 'Business catalog',
                'verbose_name_plural': 'Business catalogs',
            },
        ),
        migrations.CreateModel(
            name='CatalogDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('name', models.CharField(max_length=255, verbose_name='Dependency name')),
                ('annual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Annual maintenance cost')),
                ('observation', models.TextField(blank=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_catalog_deps', to='core.asset')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='delivery.businesscatalog')),
                ('folder', models.ForeignKey(default=iam.models.Folder.get_root_folder_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder')),
            ],
            options={
                'verbose_name': 'Catalog dependency',
                'verbose_name_plural': 'Catalog dependencies',
            },
        ),
    ]
