# Generated by Django 6.0.6 on 2026-07-21 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_businesscatalog_catalogdependency'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='plantask',
            name='plantask_exactly_one_target',
        ),
        migrations.RemoveField(
            model_name='clientintake',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='clientintake',
            name='assets_seed',
        ),
        migrations.RemoveField(
            model_name='clientintake',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='clientintake',
            name='country',
        ),
        migrations.RemoveField(
            model_name='clientintake',
            name='employee_count',
        ),
        migrations.RemoveField(
            model_name='clientintake',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='clientintake',
            name='primary_frameworks',
        ),
        migrations.RemoveField(
            model_name='engagement',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='engagement',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='engagement',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='engagement',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='engagementphase',
            name='organisation_objective',
        ),
        migrations.RemoveField(
            model_name='plantask',
            name='task_template',
        ),
    ]
