# Generated by Django 6.0.6 on 2026-07-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_remove_plantask_plantask_exactly_one_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscatalog',
            name='currency',
            field=models.CharField(blank=True, choices=[('€', 'Euro (€)'), ('R$', 'Real (R$)'), ('$', 'Dólar (US$)'), ('£', 'Libra (£)'), ('CHF', 'Franco suíço (CHF)'), ('A$', 'Dólar australiano (A$)'), ('C$', 'Dólar canadense (C$)'), ('¥', 'Iene (¥)'), ('MX$', 'Peso mexicano (MX$)'), ('ZAR', 'Rand (ZAR)')], default='', max_length=8, verbose_name='Currency (blank = global default)'),
        ),
    ]
