# Generated by Django 6.0.6 on 2026-07-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_businesscatalog_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientintake',
            name='sector',
            field=models.CharField(blank=True, choices=[('financial', 'Mercado financeiro'), ('health', 'Saúde'), ('tech', 'Tecnologia & Telecom'), ('retail', 'Varejo & Consumo'), ('industry', 'Indústria'), ('energy', 'Energia & Utilities'), ('public', 'Setor público & Terceiro setor'), ('services', 'Serviços profissionais'), ('other', 'Outro / híbrido')], max_length=40),
        ),
        migrations.AlterField(
            model_name='clientintake',
            name='subsector',
            field=models.CharField(blank=True, choices=[('bank_commercial', 'Banco comercial / múltiplo'), ('bank_investment', 'Banco de investimento'), ('credit_union', 'Cooperativa de crédito'), ('credit_finance', 'Financeira / crédito (SCFI)'), ('payment_institution', 'Instituição de pagamento / adquirência'), ('fintech_credit', 'Fintech de crédito (SCD / SEP)'), ('consortium', 'Administradora de consórcio'), ('fx', 'Câmbio / corretora de câmbio'), ('crypto_vasp', 'Criptoativos / exchange (VASP)'), ('broker_dtvm', 'Corretora / DTVM'), ('asset_manager', 'Gestora de recursos (asset)'), ('fiduciary_admin', 'Administrador fiduciário'), ('wealth_private', 'Wealth / private banking'), ('family_office', 'Family office'), ('market_infra', 'Bolsa / infraestrutura de mercado'), ('securitizer_fidc', 'Securitizadora / FIDC'), ('insurer', 'Seguradora'), ('reinsurer', 'Resseguradora'), ('insurance_broker', 'Corretora de seguros'), ('capitalization', 'Capitalização'), ('pension_open', 'Previdência aberta (EAPC)'), ('pension_closed', 'Previdência fechada (EFPC)'), ('health_plan', 'Operadora de saúde'), ('hospital', 'Hospital'), ('clinic', 'Clínica / consultório'), ('lab', 'Laboratório / diagnóstico'), ('pharma', 'Indústria farmacêutica'), ('healthtech', 'Healthtech / telemedicina'), ('saas', 'SaaS / software'), ('telecom', 'Telecom'), ('cloud_dc', 'Cloud / data center'), ('platform', 'Marketplace / plataforma digital'), ('cybersec', 'Cibersegurança'), ('retail_physical', 'Varejo físico'), ('ecommerce', 'E-commerce'), ('wholesale', 'Atacado / distribuição'), ('cpg', 'Bens de consumo'), ('manufacturing', 'Manufatura'), ('automotive', 'Automotivo'), ('food_bev', 'Alimentos & bebidas'), ('chemical', 'Química / petroquímica'), ('construction', 'Construção / engenharia'), ('power', 'Energia elétrica'), ('oil_gas', 'Óleo & gás'), ('sanitation', 'Saneamento'), ('mining', 'Mineração'), ('gov', 'Administração pública'), ('state_owned', 'Empresa estatal'), ('ngo', 'ONG / terceiro setor'), ('legal', 'Jurídico'), ('accounting', 'Contábil / auditoria'), ('consulting', 'Consultoria'), ('education', 'Educação / edtech'), ('logistics', 'Logística & transporte'), ('agro', 'Agronegócio'), ('other', 'Outro / híbrido')], max_length=60),
        ),
    ]
