# Generated by Django 6.0.6 on 2026-07-22 14:09

import django.db.models.deletion
import iam.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0172_view_compliance_assessment_full_permission'),
        ('delivery', '0007_clientintake_sector_alter_clientintake_subsector'),
        ('iam', '0022_user_is_scim_managed_user_scim_external_id_idpgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('currency', models.CharField(blank=True, default='', max_length=8, verbose_name='Currency (blank = global default)')),
                ('vendor_forensics', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('vendor_legal', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('other_external', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('regulatory_fines', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('downtime_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('folder', models.ForeignKey(default=iam.models.Folder.get_root_folder_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder')),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ir_cost', to='core.incident')),
            ],
            options={
                'verbose_name': 'Incident cost',
                'verbose_name_plural': 'Incident costs',
            },
        ),
        migrations.CreateModel(
            name='IncidentPhase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('day_start', models.SmallIntegerField(default=0)),
                ('day_end', models.SmallIntegerField(default=1)),
                ('objective', models.TextField(blank=True)),
                ('folder', models.ForeignKey(default=iam.models.Folder.get_root_folder_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ir_phases', to='core.incident')),
            ],
            options={
                'verbose_name': 'Incident phase',
                'verbose_name_plural': 'Incident phases',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='IncidentResponsePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('standard', models.CharField(choices=[('nist-800-61', 'NIST SP 800-61'), ('iso-27035', 'ISO/IEC 27035')], default='nist-800-61', max_length=20)),
                ('anchor_date', models.DateTimeField(blank=True, null=True)),
                ('modules', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20)),
                ('exec_summary', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_response_plans', to='delivery.engagement')),
                ('folder', models.ForeignKey(default=iam.models.Folder.get_root_folder_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder')),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response_plan', to='core.incident')),
            ],
            options={
                'verbose_name': 'Incident response plan',
                'verbose_name_plural': 'Incident response plans',
            },
        ),
        migrations.CreateModel(
            name='IncidentRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('role', models.CharField(choices=[('incident_commander', 'Incident commander'), ('comms_lead', 'Communications lead'), ('tech_forensics', 'Technical / forensics'), ('legal_dpo', 'Legal / DPO'), ('scribe', 'Scribe'), ('exec_sponsor', 'Executive sponsor'), ('liaison', 'Liaison')], max_length=30)),
                ('raci', models.CharField(choices=[('responsible', 'Responsible'), ('accountable', 'Accountable'), ('consulted', 'Consulted'), ('informed', 'Informed')], default='responsible', max_length=15)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ir_roles', to='core.actor')),
                ('folder', models.ForeignKey(default=iam.models.Folder.get_root_folder_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ir_roles', to='core.incident')),
            ],
            options={
                'verbose_name': 'Incident role',
                'verbose_name_plural': 'Incident roles',
            },
        ),
        migrations.CreateModel(
            name='IncidentStakeholder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('name', models.CharField(max_length=255)),
                ('party', models.CharField(choices=[('internal', 'Internal'), ('customer', 'Customer'), ('regulator', 'Regulator'), ('vendor', 'Vendor'), ('partner', 'Partner'), ('media', 'Media / press'), ('law_enforcement', 'Law enforcement')], default='internal', max_length=20)),
                ('channel', models.CharField(blank=True, max_length=120)),
                ('cadence', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ir_stakeholders', to='core.actor')),
                ('folder', models.ForeignKey(default=iam.models.Folder.get_root_folder_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ir_stakeholders', to='core.incident')),
            ],
            options={
                'verbose_name': 'Incident stakeholder',
                'verbose_name_plural': 'Incident stakeholders',
            },
        ),
        migrations.CreateModel(
            name='IncidentResponseTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('template_key', models.CharField(blank=True, db_index=True, max_length=150)),
                ('applied_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ir_task', to='core.appliedcontrol')),
                ('folder', models.ForeignKey(default=iam.models.Folder.get_root_folder_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ir_tasks', to='core.incident')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='delivery.incidentphase')),
            ],
            options={
                'verbose_name': 'Incident response task',
                'verbose_name_plural': 'Incident response tasks',
                'ordering': ['phase__order', 'order'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('template_key', ''), _negated=True), fields=('incident', 'template_key'), name='unique_irtask_template_key_per_incident')],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('regulator', models.CharField(max_length=80)),
                ('module_key', models.CharField(blank=True, max_length=40)),
                ('obligation_ref', models.CharField(blank=True, max_length=255)),
                ('deadline_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('qualitative_note', models.TextField(blank=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('acknowledged', 'Acknowledged'), ('not_applicable', 'Not applicable')], default='pending', max_length=20)),
                ('channel', models.CharField(blank=True, max_length=120)),
                ('template_text', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('evidences', models.ManyToManyField(blank=True, related_name='ir_notifications', to='core.evidence')),
                ('folder', models.ForeignKey(default=iam.models.Folder.get_root_folder_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ir_notifications', to='core.incident')),
            ],
            options={
                'verbose_name': 'Regulatory notification',
                'verbose_name_plural': 'Regulatory notifications',
                'constraints': [models.UniqueConstraint(fields=('incident', 'module_key', 'obligation_ref'), name='unique_regnotif_per_incident_module_ref')],
            },
        ),
    ]
