# Generated by Django 6.0.6 on 2026-07-22 15:18

import django.db.models.deletion
import iam.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0172_view_compliance_assessment_full_permission'),
        ('delivery', '0008_incidentcost_incidentphase_incidentresponseplan_and_more'),
        ('iam', '0022_user_is_scim_managed_user_scim_external_id_idpgroup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentTimeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField()),
                ('billable', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('applied_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ir_time_entries', to='core.appliedcontrol')),
                ('folder', models.ForeignKey(default=iam.models.Folder.get_root_folder_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ir_time_entries', to='core.incident')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ir_time_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident time entry',
                'verbose_name_plural': 'Incident time entries',
            },
        ),
    ]
