# Generated by Django 6.0.6 on 2026-07-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_incidenttimeentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidentstakeholder',
            options={'ordering': ['order', 'party'], 'verbose_name': 'Incident stakeholder', 'verbose_name_plural': 'Incident stakeholders'},
        ),
        migrations.AddField(
            model_name='incidentstakeholder',
            name='contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='incidentstakeholder',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentstakeholder',
            name='message_template',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incidentstakeholder',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incidentstakeholder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('notified', 'Notified'), ('acknowledged', 'Acknowledged'), ('not_required', 'Not required')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='incidentstakeholder',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='incidentstakeholder',
            name='when_to_notify',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('on_escalation', 'On escalation / crisis'), ('on_resolution', 'On resolution'), ('periodic', 'Periodic'), ('on_request', 'On request')], default='on_escalation', max_length=20),
        ),
    ]
